language: python

python:
  - "3.8.3"

services:
  - postgresql

env:
  - DJANGO=3.0.7 DB=postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE USER test WITH PASSWORD '';" -U postgres
  - psql -c "ALTER USER test CREATEDB;" -U postgres

script:
  - python manage.py test
