language: python

python:
  - "3.8.3"

services:
  - postgresql

env: # => 4
  - DJANGO=3.0.7 DB=postgresql

install:
  - pip install -r requirements.txt
  
before_script: # => 6
  - postgresql -e 'create database test;' -u colette

script:
  - python manage.py test
