language: python

python:
  - "3.8.3"

services:
  - postgres

env:
  - DJANGO=3.0.7 DB=postgres

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - python manage.py test
